/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquinavirtual;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Hugo
 */
public class MaquinaVirtual extends javax.swing.JFrame {
    private DefaultListModel<String> romList = new DefaultListModel<>();
    private DefaultListModel<String> ramList = new DefaultListModel<>();
    private ArrayList<String> listRom = new ArrayList<>();
    /**
     * Creates new form GUI
     */
    public MaquinaVirtual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        scrollRAM = new javax.swing.JScrollPane();
        valorRAM = new javax.swing.JList<>();
        rom = new javax.swing.JLabel();
        scrollROM = new javax.swing.JScrollPane();
        valorROM = new javax.swing.JList<>();
        a = new javax.swing.JLabel();
        valorA = new javax.swing.JTextField();
        d = new javax.swing.JLabel();
        valorD = new javax.swing.JTextField();
        m = new javax.swing.JLabel();
        valorM = new javax.swing.JTextField();
        pc = new javax.swing.JLabel();
        valorPC = new javax.swing.JTextField();
        botonPasoAPaso = new javax.swing.JButton();
        botonTodo = new javax.swing.JButton();
        barra = new javax.swing.JMenuBar();
        barraArchivo = new javax.swing.JMenu();
        archivoAbrir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Maquina Virtual");
        titulo.setToolTipText("");

        ram.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ram.setForeground(new java.awt.Color(0, 0, 0));
        ram.setText("RAM:");

        valorRAM.setModel(ramList);
        valorRAM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollRAM.setViewportView(valorRAM);

        rom.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rom.setForeground(new java.awt.Color(0, 0, 0));
        rom.setText("ROM:");

        valorROM.setModel(romList);
        valorROM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollROM.setViewportView(valorROM);

        a.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        a.setForeground(new java.awt.Color(0, 0, 0));
        a.setText("A");

        valorA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        d.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        d.setForeground(new java.awt.Color(0, 0, 0));
        d.setText("D");

        valorD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        m.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        m.setForeground(new java.awt.Color(0, 0, 0));
        m.setText("M");

        valorM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        pc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pc.setForeground(new java.awt.Color(0, 0, 0));
        pc.setText("PC");

        valorPC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        botonPasoAPaso.setText("Ejecutar Paso a Paso");

        botonTodo.setText("Ejecutar Todo");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ram))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollROM, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rom))
                        .addGap(50, 50, 50))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(botonPasoAPaso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonTodo)
                        .addGap(108, 108, 108))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addComponent(a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addComponent(d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m)
                    .addComponent(pc))
                .addGap(12, 12, 12)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorPC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(10, 10, 10)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ram)
                    .addComponent(rom))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollROM, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a)
                    .addComponent(m))
                .addGap(30, 30, 30)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorPC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d)
                    .addComponent(pc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPasoAPaso)
                    .addComponent(botonTodo))
                .addGap(28, 28, 28))
        );

        barraArchivo.setText("Archivo");

        archivoAbrir.setText("Abrir Archivo");
        archivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoAbrirActionPerformed(evt);
            }
        });
        barraArchivo.add(archivoAbrir);

        barra.add(barraArchivo);

        setJMenuBar(barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoAbrirActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(MaquinaVirtual.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            try {
                BufferedReader bf = new BufferedReader(new FileReader(file));
                String cadena;
        
                for (int x = 0 ; (cadena = bf.readLine()) != null ; x++) {
                    this.romList.addElement(cadena);
                    this.listRom.add(cadena);
                } 
                this.rellenarRAM();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MaquinaVirtual.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MaquinaVirtual.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_archivoAbrirActionPerformed
    
    public void rellenarRAM(){
        for(int x=0 ; x<= 32768 ; x++){
            this.ramList.addElement("0000000000000000");
        }
    }
    
    public void separacionDeBits(){
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaquinaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaquinaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaquinaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaquinaVirtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaquinaVirtual().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JMenuItem archivoAbrir;
    private javax.swing.JPanel background;
    private javax.swing.JMenuBar barra;
    private javax.swing.JMenu barraArchivo;
    private javax.swing.JButton botonPasoAPaso;
    private javax.swing.JButton botonTodo;
    private javax.swing.JLabel d;
    private javax.swing.JLabel m;
    private javax.swing.JLabel pc;
    private javax.swing.JLabel ram;
    private javax.swing.JLabel rom;
    private javax.swing.JScrollPane scrollRAM;
    private javax.swing.JScrollPane scrollROM;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField valorA;
    private javax.swing.JTextField valorD;
    private javax.swing.JTextField valorM;
    private javax.swing.JTextField valorPC;
    private javax.swing.JList<String> valorRAM;
    private javax.swing.JList<String> valorROM;
    // End of variables declaration//GEN-END:variables
}
